-- Bayi şablonu v2: kullanıcının verdiği gerçek sözleşme metni (bayi sözleşmesi.docx, 12 bölüm / 79 madde)
update sozlesme_sablonlari
set govde = $SABLON$YETKİLİ DIŞ BAYİLİK VE DEAL REGISTER SÖZLEŞMESİ
Kanal Yönetimi, Ticari Koruma, Sipariş ve Tahsilat, Gizlilik, KVKK, Etik Uyum ve İyi Niyet Hükümleri

Sözleşme Tarihi : {{sozlesme_tarihi}}
Sözleşme No     : {{sozlesme_no}}
ZNA             : ZNA Teknoloji Bilişim Hizmetleri Sanayi ve Ticaret Ltd. Şti.
Bayi            : {{bayi_unvani}}
Bayi Statüsü    : {{yetkili_satici_statusu}}
Yıllık Hedef    : {{bayi_yillik_hedef}}
Süre            : {{sozlesme_suresi}}
Sözleşme Niteliği: Tek metin halinde; tüm hükümler ayrılmaz bütündür

Bu sözleşme, taraflar arasında ayrıca imzalanacak bağımsız bir gizlilik, etik, KVKK, ödeme veya Deal Register protokolü olmaksızın; bu alanlardaki tüm hak ve yükümlülükleri tek başına ve bütün olarak düzenler.

1. TARAFLAR, TANIMLAR VE SÖZLEŞMENIN KONUSU
1.1. Taraflar. İşbu sözleşmede ZNA Teknoloji Bilişim Hizmetleri Sanayi ve Ticaret Ltd. Şti. “ZNA”; ticari unvanı, adresi ve yetkilileri imza bölümünde yer alan taraf “Bayi” olarak anılır. ZNA ve Bayi ayrı ayrı “Taraf”, birlikte “Taraflar”dır.
1.2. Tanımlar. “Ürün/Hizmet”; donanım, yazılım, lisans, abonelik, video analitik, güvenlik teknolojisi, entegrasyon, teknik destek, eğitim, bakım, danışmanlık, demo ve PoC hizmetlerini; “Müşteri” son kullanıcıyı veya proje sahibini; “Deal Register” müşteri/fırsat/proje bilgilerinin ZNA sistemine kaydı ve ZNA tarafından yazılı onayını; “Özel Ticari Koşul” proje bazlı fiyat, iskonto, vade, stok rezervasyonu, demo, PoC veya ticari desteği ifade eder.
1.3. Konu. ZNA, Bayi’ye yalnızca işbu sözleşme, yazılı ZNA onayı, güncel ürün koşulları ve Deal Register prosedürü çerçevesinde tanıtım, fırsat geliştirme ve satış yapma hakkı verir. Bu yetki münhasır olmayan, devredilemeyen, geri alınabilir ve ZNA adına taahhüt altına girme yetkisi vermeyen sınırlı bir ticari yetkidir.
1.4. Tek Metin İlkesi. Taraflar, başta Deal Register, fiyatlandırma, sipariş, ödeme, teminat, gizlilik, KVKK, etik, çıkar çatışması, marka kullanımı, denetim, yaptırım ve fesih olmak üzere tüm konuların bu tek sözleşmede düzenlendiğini; e-posta, teklif, fiyat listesi ve yazılı ZNA talimatlarının yalnızca bu sözleşmeye aykırı olmamak kaydıyla uygulama belgesi niteliğinde olduğunu kabul eder.
2. BAYILIK STATÜSÜ, YETKI SINIRLARI VE ZNA’NIN SAKLI HAKLARI
2.1. Münhasır Olmama. Bayiye herhangi bir bölge, müşteri grubu, sektör, ürün veya proje bakımından münhasırlık verilmemiştir. ZNA; başka bayiler atayabilir, yeni kanal kurabilir, aynı müşteri veya proje için doğrudan çalışabilir, fiyat verebilir, sipariş alabilir veya başka bir partneri görevlendirebilir.
2.2. Bağımsız Tacirlik. Bayi; ZNA’nın acentesi, temsilcisi, işçisi, franchise alanı, distribütörü veya ortak girişim ortağı değildir. Bayi, kendi çalışanları, vergi, SGK, iş sağlığı ve güvenliği, kira, seyahat, teklif hazırlama, satış, kurulum organizasyonu ve son kullanıcıya verdiği vaatlerden tek başına sorumludur.
2.3. Bağlayıcı İşlem Yasağı. Bayi, ZNA adına sözleşme imzalayamaz, borç altına sokamaz, garanti süresi/teslimat/fiyat taahhüdü veremez, tahsilat yapamaz, kamuya açıklama yapamaz veya ZNA’yı bağlayan beyanda bulunamaz. ZNA adına yapılan her işlem için önceden açık yazılı yetki şarttır.
2.4. Yetkinin Askıya Alınması. ZNA; finansal risk, gecikmiş borç, etik/uyum şüphesi, veri güvenliği riski, yanlış beyan, müşteri şikayeti, hedef geriliği veya marka itibarını etkileyen herhangi bir durum halinde Bayi’nin fiyat erişimini, Deal Register kullanımını, stok/teslimat, lisans açma, teknik destek veya yeni sipariş yetkisini derhal askıya alabilir.
2.5. Yıllık Performans Kriteri. Bayi için yıllık hedef 25.000 USD tahsil edilmiş net cirodur. Hedef; bayi statüsünün, iskonto seviyesinin ve ticari erişimlerin devamı için performans kriteridir. ZNA, üç aylık dönemlerde tahsilat disiplini, müşteri memnuniyeti, teknik yetkinlik, proje kalitesi ve uyum performansını değerlendirebilir.
3. DEAL REGISTER, PROJE KORUMASI VE TEKLIF DISIPLINI
3.1. Ön Kayıt Zorunluluğu. Bayi; müşteri adı, vergi/kurum bilgisi, lokasyon, karar verici, ihtiyaç, tahmini bütçe, ürün kapsamı, rakip durumu, zaman planı ve kendi katkısını eksiksiz sunmadan Deal Register talep edemez. Eksik, yanıltıcı, daha önce bilinen veya başka kanal tarafından kaydedilmiş bilgiler için hak doğmaz.
3.2. ZNA Onayı Olmadan Ticari İşlem Yasağı. ZNA tarafından yazılı olarak onaylanmış Deal Register kaydı bulunmadan Bayi’ye ilgili fırsat bakımından özel proje fiyatı, bayi fiyatı, indirim, resmi teklif, teknik tasarım, demo/PoC, lisans, stok rezervasyonu, ödeme kolaylığı, saha desteği veya ticari doküman verilmez. ZNA’nın genel katalog veya kamuya açık bilgileri bu kuralın istisnası değildir.
3.3. Onay Süreci. ZNA, Deal Register kaydını kendi takdirinde inceler; ek bilgi isteyebilir, reddedebilir, farklı bayiyle çakışma belirleyebilir veya doğrudan yönetim kararı alabilir. Sessizlik onay anlamına gelmez. Onay yalnızca yazılı ZNA teyidi ile doğar.
3.4. Deal Register Geçerlilik Süresi, Faaliyet Takibi ve Uzatma. ZNA tarafından yazılı olarak onaylanan her Deal Register kaydı, ZNA onay yazısında daha kısa bir süre belirtilmemişse onay tarihinden itibaren doksan (90) gün süreyle geçerlidir. Bayi, bu ilk 90 günlük süre boyunca fırsatın aktif biçimde yönetildiğini; son kullanıcı görüşmesi, keşif, teknik toplantı, ihtiyaç analizi, çözüm tasarımı, teklif çalışması, demo/PoC, satın alma süreci, karar verici temasları veya benzeri somut faaliyetlerle belgelemekle yükümlüdür. ZNA; CRM/Deal Register kayıtları, toplantı notları, e-posta yazışmaları, müşteri teyidi, teknik dokümanlar, demo/PoC raporları, teklif geri bildirimleri ve diğer makul delilleri talep edebilir.

İlk 90 gün içinde yeterli ve doğrulanabilir faaliyet bulunmaması, müşteri bilgisinin yanıltıcı/eksik olması, Bayi’nin kayıt güncellemelerini yapmaması veya projenin fiilen ilerlemediğinin anlaşılması halinde kayıt, ayrıca ihtar gerekmeksizin ZNA tarafından pasife alınabilir veya iptal edilebilir. Bu durumda Bayi, proje koruması, özel fiyat, indirim, stok rezervasyonu, demo/PoC, teknik/ticari destek veya müşteri üzerinde herhangi bir hak iddia edemez.

Bayi, ilk 90 günün bitiminden önce yazılı uzatma talebinde bulunabilir. ZNA, yalnızca somut ilerleme ve Bayi performansını yeterli görmesi halinde, kendi takdirinde bir defaya mahsus en fazla otuz (30) gün ilave süre tanıyabilir. Demo veya PoC uygulanmış olması ve bunun kapsam, tarih, sonuç, müşteri katılımı ve takip aksiyonlarıyla belgelenmesi halinde ZNA ayrıca en fazla otuz (30) gün daha uzatma verebilir. Demo/PoC sonrasında satın alma veya nihai karar sürecinin tamamlanması için ZNA’nın yazılı onayıyla en fazla on beş (15) gün ek kapanış süresi tanınabilir. Böylece Deal Register koruma süresi, ZNA’nın her aşamadaki yazılı onayı şartıyla toplamda en fazla yüz altmış beş (165) güne ulaşabilir.

Süre uzatımları otomatik değildir; sessizlik, e-posta trafiği, sözlü beyan, müşteri ilgisi veya Bayi’nin tek taraflı beyanı uzatma anlamına gelmez. ZNA, her uzatma talebini reddetme, daha kısa süre verme, ek belge/teminat isteme, kayıt kapsamını daraltma, fiyat/iskonto koşullarını değiştirme, kaydı başka bir bayiyle paylaşma veya doğrudan yönetme hakkını saklı tutar. Kayıt süresi sonunda yazılı sipariş, ZNA tarafından teyit edilmiş satış aşaması veya ZNA’nın kabul ettiği somut ilerleme bulunmuyorsa Deal Register kendiliğinden serbest kalır; ZNA, ilgili müşteri/projeyle doğrudan veya dilediği başka bayi/iş ortağı üzerinden çalışma hakkına sahip olur. Bayi, serbest kalan veya iptal edilen kayıt bakımından hak, komisyon, tazminat, zarar veya müşteri sahipliği iddiasında bulunamaz.
3.5. Kayıt Sahibinin Yükümlülüğü. Bayi; müşteri temaslarını, teklif geri bildirimlerini, rakip bilgisini, bütçe/takvim değişikliklerini ve riskleri doğru ve güncel biçimde ZNA’ya aktarır. Yanlış, eksik veya gecikmiş kayıt; proje korumasının kaybına ve ticari avantajların geri alınmasına neden olabilir.
3.6. Müşteri ve Proje Korumasının Sınırı. Deal Register, Bayi’ye müşterinin tamamı üzerinde mutlak veya kalıcı hak vermez. Koruma yalnızca ZNA’nın yazılı olarak onayladığı müşteri, lokasyon, kapsam ve süre ile sınırlıdır. Yeni kapsam, farklı lokasyon, yeni ihale, farklı karar birimi veya önemli kapsam değişikliği için yeniden kayıt gerekir.
3.7. Baypas ve Haksız Yönlendirme. Bayi; ZNA’yı devre dışı bırakacak şekilde üretici, tedarikçi, başka bayi, son kullanıcı veya üçüncü taraf üzerinden aynı ürün/hizmete erişmeye çalışamaz; ZNA’nın müşterisini, çalışanını veya kayıtlı fırsatını başka kanala yönlendiremez. Bu davranış ağır ihlal sayılır.
3.8. Çakışan Fırsatlar. Çakışan kayıt veya hak sahipliği ihtilafında ZNA kayıtları, müşteri doğrulaması, ilk somut faaliyet, teknik emek, finansal güvenilirlik ve proje yönetim kabiliyetini birlikte değerlendirerek nihai karar verir. ZNA’nın kararı ticari ilişki bakımından bağlayıcıdır.
3.9. Rekabet Hukuku Uyumlu Fiyatlama. Bayi, son kullanıcıya uygulayacağı satış fiyatını bağımsız belirler. ZNA’nın teklif/fiyatlandırma onayı, yalnızca Bayi’ye satış koşulları, proje maliyeti, stok, kredi riski, marka/teknik doğruluk ve Deal Register yönetimi içindir; Bayi’nin son kullanıcı fiyatını zorunlu olarak belirleme amacı taşımaz.
3.10. İhlal Sonuçları. Deal Register ihlalinde ZNA; kaydı iptal etme, proje korumasını kaldırma, özel fiyatı geri çekme, teslimat/lisans/desteği durdurma, bayi seviyesini düşürme, sözleşmeyi derhal feshetme ve tüm doğrudan/dolaylı zararlarını talep etme hakkına sahiptir.
4. TEKLIF, SIPARIŞ, FIYAT, TESLIMAT VE İADE
4.1. Teklif Geçerliliği. ZNA teklifleri yazılı olarak belirtilen süre boyunca geçerlidir. Süre belirtilmemişse teklif 7 gün geçerlidir. ZNA; kur, tedarik maliyeti, üretici fiyatı, lojistik, stok, vergi, mevzuat veya proje koşullarındaki değişiklikler nedeniyle sipariş teyidinden önce teklifini değiştirebilir veya geri çekebilir.
4.2. Siparişin Bağlayıcılığı. Sipariş, ancak ZNA’nın yazılı sipariş teyidi, ödeme/teminat şartlarının sağlanması ve varsa Deal Register onayı ile bağlayıcı olur. Bayi sipariş formu, e-posta talebi, ödeme planı veya sözlü beyan tek başına ZNA için kabul anlamına gelmez.
4.3. Fiyat ve Vergiler. Tüm fiyatlar aksi yazılı belirtilmedikçe KDV, damga vergisi, gümrük, nakliye, sigorta, saha, kurulum, konfigürasyon, devreye alma, eğitim, seyahat, konaklama ve üçüncü taraf giderleri hariçtir. ZNA fiyatları; liste, proje veya kampanya bazlı değişebilir.
4.4. Teslimat ve Risk. Teslim süreleri tahminidir; tedarikçi, lojistik, gümrük, mücbir sebep, ödeme gecikmesi veya teknik/izin süreçleri nedeniyle uzayabilir. Aksi yazılı kararlaştırılmadıkça ürünün Bayi’ye veya taşıyıcıya teslimiyle ziya/hasar riski Bayi’ye geçer.
4.5. Kısmi Sevkiyat. ZNA kısmi sevkiyat yapabilir ve her sevkiyatı ayrı faturalandırabilir. Bayi, kısmi sevkiyat nedeniyle siparişi iptal, ödeme erteleme veya tazminat talebi ileri süremez.
4.6. Muayene ve Ayıp Bildirimi. Bayi, ürünleri teslimde derhal kontrol eder; görünür ayıp, eksik veya hasarı en geç 3 iş günü içinde yazılı ve belgeli bildirir. Süresinde bildirilmemiş iddialar kabul edilmiş sayılır. Gizli ayıp iddiaları, tespit edildiği anda ve en geç garanti süresi içinde belgeli olarak bildirilir.
4.7. İade. İade yalnızca ZNA’nın önceden yazılı onayıyla mümkündür. Müşteriye/ projeye özel tedarik edilen, lisansı açılmış, yazılım aktivasyonu yapılmış, ambalajı bozulmuş, kullanılmış, eski seri veya satılabilir niteliğini kaybetmiş ürünler iade alınmaz. Kabul edilen iadelerde ZNA; yeniden stoklama, test, nakliye, kur farkı, tedarikçi kesintisi ve değer kaybını mahsup eder.
4.8. Garanti. Garanti, yalnızca üretim kaynaklı ayıplar için ve üretici/ürün koşulları ile sınırlıdır. Yanlış montaj, uygunsuz ortam, enerji/ağ altyapısı, üçüncü taraf müdahalesi, yetkisiz yazılım, kullanıcı hatası, bakım eksikliği veya ürün talimatına aykırı kullanım garanti dışıdır.
5. ÖDEME, VADE, TEMINAT, TAHSILAT VE FINANSAL GÜVENCE
5.1. Peşin Ödeme Esası. Aksi ZNA tarafından yazılı olarak onaylanmadıkça tüm siparişler peşin ödeme esasına tabidir. Ödeme, ZNA’nın yazılı olarak bildirdiği kendi adına kayıtlı banka hesabına yapılır. Elden, üçüncü kişi hesabına, kripto varlıkla veya belgesiz tahsilat kabul edilmez.
5.2. Vade İstisnası. Vade yalnızca ZNA’nın her sipariş için ayrı ve yazılı kredi onayı vermesi halinde uygulanır. Vade onayı; gelecekteki siparişler için emsal, kazanılmış hak veya sürekli kredi limiti oluşturmaz. ZNA, risk değerlendirmesiyle herhangi bir anda vade tanımayı reddedebilir, limiti azaltabilir veya peşin ödemeye dönebilir.
5.3. Vade Süresi. ZNA’nın yazılı onayı olmadan 30 günü aşan vade verilemez. Vade başlangıcı, faturanın düzenlenmesi değil ZNA’nın yazılı sipariş teyidinde belirtilen tarihtir. Kısmi ödeme, vadeyi uzatmaz ve ZNA’nın kalan bedel üzerindeki haklarını etkilemez.
5.4. Kur ve Faturalama. Döviz bazlı bedellerin TL tahsilatında, aksi teklif üzerinde belirtilmedikçe fatura/ödeme günündeki TCMB döviz satış kuru veya ZNA’nın teklifinde belirtilen kur uygulanır. Kur farkı, vergi, resim, harç ve finansman maliyetleri Bayi’ye aittir.
5.5. Temerrüt. Bayi’nin vadesinde ödeme yapmaması halinde ZNA ayrıca ihtara gerek olmaksızın temerrüt faizini, kanuni ticari faiz ve sözleşmesel gecikme maliyetlerini talep edebilir. Temerrüt, tüm borçları muaccel kılar; ZNA sevkiyat, lisans, aktivasyon, destek, garanti işlemi ve yeni siparişleri durdurabilir.
5.6. Teminat. ZNA; çek, senet, banka teminat mektubu, kefalet, alacak temliki, kredi kartı provizyonu, depozito veya başka uygun teminat talep edebilir. Teminat sağlanmaması, yetersiz kalması veya değer kaybetmesi halinde ZNA ifayı durdurabilir. Teminat, Bayi’nin tüm mevcut ve gelecekte doğacak borçlarına karşı kullanılabilir.
5.7. Takas, Mahsup ve Hapis. ZNA; Bayi’ye karşı her türlü muaccel alacağını, Bayi’ye ait alacak, iade, prim, iskonto, teminat veya ödeme ile takas ve mahsup edebilir. Bayi, ZNA’nın yazılı izni olmadan takas/mahsup, ödeme kesintisi, hakediş durdurma veya tek taraflı indirim yapamaz.
5.8. Mülkiyetin Saklı Tutulması. Bedeli tamamen tahsil edilinceye kadar ürünlerin mülkiyeti ZNA’da kalır. Bayi, ürünleri rehnedemez, teminat gösteremez, üçüncü kişiye devredemez veya haciz/iflas riski doğuran işleme konu edemez. ZNA, ödenmemiş ürünleri bulunduğu yerden geri alma hakkına sahiptir.
5.9. Tahsilat Giderleri. Bayi; gecikme nedeniyle doğan avukatlık, icra, arabuluculuk, dava, ekspertiz, nakliye, depo, kur farkı, finansman, denetim ve tahsilat masraflarından sorumludur.
5.10. Finansal Bilgi ve Erken Uyarı. Bayi; iflas, konkordato, haciz, ödeme güçlüğü, kredi limitinin düşmesi, ortaklık değişikliği, önemli dava/icra takibi veya finansal durumunu etkileyen olayı en geç 2 iş günü içinde ZNA’ya bildirir. Bildirmemek ağır ihlaldir.
6. GIZLILIK, TICARI SIR VE BILGI GÜVENLIĞI
6.1. Gizli Bilgi. Fiyat, iskonto, marj, müşteri, Deal Register, teklif, teknik çizim, mimari, kaynak kodu, lisans bilgisi, şifre, erişim kaydı, satış stratejisi, personel, sözleşme, finansal bilgi, demo, PoC ve ZNA tarafından açıklanan her türlü yazılı, sözlü, görsel veya elektronik bilgi gizlidir.
6.2. Kullanım Sınırı. Bayi, gizli bilgiyi yalnızca işbu sözleşmenin amacı için, bilmesi gereken çalışanlarıyla ve aynı derecede gizlilik yükümlülüğü altında paylaşabilir. Gizli bilgiyi çoğaltamaz, tersine mühendislikte kullanamaz, rakip/tedarikçi/üçüncü kişiyle paylaşamaz veya kendi ticari menfaati için kullanamaz.
6.3. Güvenlik Tedbirleri. Bayi; güçlü parola ve çok faktörlü doğrulama, erişim yetkisi, kayıt/log, güncel güvenlik yazılımı, şifreleme, güvenli yedekleme, fiziksel erişim kontrolü, güvenli imha ve çalışan farkındalığı dahil makul teknik ve idari tedbirleri uygular.
6.4. Olay Bildirimi. Yetkisiz erişim, sızıntı, kayıp, yanlış gönderim, şüpheli davranış veya bilgi güvenliği olayı öğrenildiğinde Bayi en geç 12 saat içinde ZNA’ya yazılı bilgi verir; olayı sınırlar, delilleri korur ve ZNA’nın talimatlarına uyar.
6.5. Süre. Gizlilik yükümlülüğü sözleşme sona erdikten sonra 5 yıl; ticari sır niteliğindeki bilgiler bakımından ise bu niteliği sürdüğü müddetçe devam eder.
6.6. İade ve İmha. ZNA talebinde veya sözleşme bitiminde Bayi, gizli bilgi ve kopyalarını en geç 5 iş günü içinde iade eder veya geri döndürülemez şekilde imha ettiğini yazılı olarak teyit eder. Yasal zorunlu saklama halleri saklıdır.
7. KIŞISEL VERILERIN KORUNMASI VE VERI İŞLEME
7.1. KVKK Uyum Yükümlülüğü. Bayi; 6698 sayılı Kişisel Verilerin Korunması Kanunu, ilgili mevzuat, Kurul kararları ve ZNA’nın yazılı veri güvenliği talimatlarına tam uyum sağlar. Kişisel verileri yalnızca hukuka uygun, belirli, açık ve meşru amaçla; gerekli ölçüde işler.
7.2. İşleme Sınırı. Bayi, ZNA müşterilerine, çalışanlarına, ziyaretçilerine veya proje kullanıcılarına ait kişisel verileri satamaz, kiralayamaz, pazarlama amacıyla kullanamaz, profilleyemez, üçüncü kişiye aktaramaz veya ZNA’nın yazılı talimatı dışında işleyemez.
7.3. Özel Nitelikli Veriler. Görüntü, ses, biyometrik, erişim, sağlık, kimlik ve benzeri hassas/özel nitelikli veri içeren projelerde Bayi artırılmış teknik ve idari güvenlik tedbirlerini uygular; erişimi rol bazlı ve kayıt altındadır.
7.4. Alt Veri İşleyen ve Yurt Dışı Aktarım. Bayi, ZNA’nın önceden yazılı izni olmadan alt veri işleyen kullanamaz; yurt dışı bulut, sunucu, destek, uzaktan erişim veya aktarım yapamaz. Onay verilse dahi Bayi, alt veri işleyenin eylemlerinden ZNA’ya karşı sorumludur.
7.5. İhlal Bildirimi. Kişisel veri ihlali veya ihlal şüphesinde Bayi en geç 12 saat içinde ZNA’ya; olayın zamanı, kapsamı, etkilenen kişi/veri türü, risk, alınan önlem ve iletişim kişisini içeren yazılı bildirim yapar. Bayi, ZNA onayı olmadan ilgili kişi, müşteri, basın veya kamu otoritesine açıklama yapamaz; kanuni zorunlulukta derhal ZNA’yı bilgilendirir.
7.6. İlgili Kişi Başvuruları. Bayi’ye ulaşan erişim, düzeltme, silme, şikayet veya otorite talebi en geç 1 iş günü içinde ZNA’ya iletilir. Bayi, ZNA’nın yazılı yönlendirmesi olmadan cevap vermez; teknik destek sağlar.
7.7. Saklama ve İmha. Kişisel veriler, amaç ve yasal süre ile sınırlı saklanır. Süre bitiminde veya ZNA talebinde güvenli biçimde silinir, yok edilir veya anonimleştirilir; işlem kayıtları ZNA’ya sunulur.
7.8. Sorumluluk. Bayi’nin kusuru veya ihlali nedeniyle doğan idari para cezası, tazminat, inceleme, danışmanlık, bildirim, itibar kaybı ve tüm masraflar Bayi’ye aittir.
8. UYUM, İTİBAR VE MARKA KORUMA
8.1. Genel İlke. Bayi; kendi ticari faaliyetlerinden, çalışanlarından, yöneticilerinden, temsilcilerinden, alt bayilerinden, alt yüklenicilerinden ve müşterileriyle yürüttüğü süreçlerden münhasıran sorumludur. ZNA ve TRASSIR markaları, Bayi’nin bağımsız ticari faaliyetlerinin tarafı, yöneticisi, temsilcisi, danışmanı veya garantörü değildir.
8.2. ZNA ve TRASSIR Markalarının Ayrıştırılması. Bayi; rüşvet, yolsuzluk, usulsüzlük, haksız rekabet, danışıklı teklif, sahte/yanıltıcı beyan, hukuka aykırı veri işleme, kamu ihalesi veya teknik şartname ihlali, çıkar çatışması, vergi/ödeme usulsüzlüğü, ceza soruşturması, idari inceleme ya da benzeri herhangi bir iddia, olay veya ihtilafta ZNA ve/veya TRASSIR markalarını, bunlara ait unvan, logo, çalışan, iş ortağı veya ürünleri doğrudan ya da dolaylı şekilde olaya dahil edemez; ilişkilendiremez; referans gösteremez; sorumlu, taraf, onay makamı veya destekleyici gibi gösteremez.
8.3. Yetkisiz Beyan ve Taahhüt Yasağı. Bayi; ZNA veya TRASSIR markaları adına ya da bu markaları temsilen açıklama, savunma, basın duyurusu, kamu kurumu yazışması, ihale beyanı, müşteri taahhüdü, fiyat/iskonto vaadi, garanti, hukuki görüş veya teknik uygunluk beyanı veremez. ZNA veya TRASSIR markalarının adının, logosunun veya referansının kullanılacağı her türlü yazılı, dijital, görsel veya sözlü iletişim için ZNA’nın önceden yazılı onayı zorunludur.
8.4. Olayın ZNA veya TRASSIR’e Sıçramasının Önlenmesi. Bayi; kendi faaliyetinden kaynaklanan veya kendisiyle bağlantılı herhangi bir inceleme, şikâyet, soruşturma, dava, ihale uyuşmazlığı, idari yaptırım, veri ihlali, kamuoyu gündemi veya itibar riski halinde, ZNA ve TRASSIR markalarının konu ile ilişkilendirilmesini önlemek için gerekli tüm tedbirleri derhal alır. Bayi, olayın ZNA veya TRASSIR markalarına yansıyabileceğini öğrendiği andan itibaren en geç yirmi dört (24) saat içinde ZNA’ya yazılı bildirim yapar; ZNA’nın talimatları dışında hiçbir açıklama yapmaz ve gerekli düzeltme/tekzip/geri çekme işlemlerini derhal yerine getirir.
8.5. Tazmin ve Masun Tutma. Bayi’nin eylemi, ihmali, beyanı, müşterisi, alt bayisi, alt yüklenicisi veya temsilcisi nedeniyle ZNA’nın ve/veya TRASSIR markalarının herhangi bir talep, idari işlem, soruşturma, dava, yaptırım, para cezası, ihale uyuşmazlığı, itibar kaybı, müşteri kaybı, kamuoyu baskısı, avukatlık ücreti, danışmanlık/inceleme gideri veya sair zarara uğraması halinde; Bayi, ZNA’nın ilk yazılı talebi üzerine tüm doğrudan zararları, makul savunma ve danışmanlık giderlerini ve üçüncü kişi taleplerinden doğan maliyetleri derhal ve nakden tazmin eder; ZNA’yı ve TRASSIR markalarını/ilgili hak sahiplerini bu taleplere karşı masun tutar. ZNA’nın bu nedenle uğradığı itibar zararının giderilmesine yönelik makul iletişim, düzeltme ve kriz yönetimi giderleri de Bayi tarafından karşılanır.
8.6. Kamu İhaleleri ve Müşteri Süreçleri. Bayi; kamu ihalesi, özel sektör satın alma süreci, teknik/idari şartname, müşteri sözleşmesi veya proje teslimi kapsamında kendi işlem ve beyanlarından sorumludur. Bayi, ZNA veya TRASSIR markalarının kullanımına ilişkin ZNA’nın önceden yazılı onayı olmadıkça bu markaları teklif veren, ihaleye katılan, taahhüt veren, ortak sorumlu, teknik şartname hazırlayan, garanti veren veya hukuki uygunluk sağlayan taraf gibi gösteremez.
8.7. Çıkar Çatışması ve İtibar Riski Bildirimi. Bayi; ZNA veya TRASSIR markalarının itibarını etkileyebilecek nitelikteki herhangi bir çıkar çatışmasını, olumsuz medya/haber içeriğini, kamu kurumu incelemesini, önemli müşteri şikâyetini, veri ihlalini, ihale şikâyetini veya ticari itibarı etkileyebilecek olayı gecikmeksizin ZNA’ya bildirir. ZNA, itibar ve marka koruma amacıyla ilgili proje, fiyat erişimi, Deal Register kaydı, sevkiyat, lisans, teknik destek veya bayi yetkisini askıya alma hakkına sahiptir.
8.8. İş Birliği ve Delil Koruma. Bayi; ZNA’nın talep ettiği ölçüde, olayla ilgili kayıtları, yazışmaları, teklifleri, müşteri bildirimlerini ve diğer belgeleri korur ve sunar; ZNA’nın savunma, inceleme, denetim ve marka koruma çalışmalarında iyi niyetli iş birliği yapar. Bu hüküm, Bayi’nin kendi hukuki sorumluluğunu ortadan kaldırmaz veya ZNA’ya veya TRASSIR markası/ilgili hak sahibine Bayi adına hareket etme yükümlülüğü yüklemez.
8.9. Biyometrik Özellikli Ürün ve Çözümlerin Hukuka Uygun Kullanımı ve Sorumluluk Dağılımı. Taraflar; yüz tanıma, parmak izi, avuç içi, iris, retina ve benzeri biyometrik özellikli ürün, yazılım, lisans, analitik, entegrasyon ve erişim kontrol çözümlerinin ZNA ürün/hizmet portföyünde yer alabileceğini ve bunların satışı, tedariki veya projeye konu edilmesinin tek başına hukuka aykırılık teşkil etmediğini kabul eder. Ancak Bayi; bu ürün ve çözümleri teklif ettiği, sattığı, kurduğu, devreye aldığı veya desteklediği her projede kullanım amacının, hukuki dayanağın, veri sorumlusu sıfatının, aydınlatma yükümlülüklerinin, gerekli açık rıza veya diğer işleme şartlarının, saklama-imha sürelerinin, erişim yetkilerinin, teknik/idari tedbirlerin, çalışan-işveren ilişkisine ilişkin özel kuralların, ihale/şartname hükümlerinin ve yürürlükteki mevzuata uygunluğun müşteri/son kullanıcı tarafından sağlanacağından emin olmakla yükümlüdür. Mesai, puantaj veya işe giriş-çıkış takibi gibi amaçlarla biyometrik veri kullanımı bakımından Bayi; ilgili mevzuat ve Kişisel Verileri Koruma Kurulu kararları uyarınca hukuka aykırılık riski bulunan uygulamalar hakkında müşteriyi yazılı olarak bilgilendirir, daha az müdahaleci alternatiflerin değerlendirilmesini önerir ve hukuka aykırı olduğu açıkça anlaşılan bir kullanım için ZNA veya TRASSIR markaları adına hiçbir taahhütte bulunmaz. Güvenlik, erişim kontrolü, ziyaretçi yönetimi, yetkisiz girişin önlenmesi, kimlik doğrulama veya mevzuatın izin verdiği diğer amaçlarla kullanılan sistemlerde veri sorumlusu; kural olarak müşteri/son kullanıcıdır ve tüm kullanım, konfigürasyon, aydınlatma, onay, saklama, paylaşım ve güvenlik süreçlerinden münhasıran sorumludur. Bayi ve müşteri/son kullanıcı; kamu ihalesi, teknik veya idari şartname, müşteri talebi, açık rıza, kurum içi prosedür veya başka herhangi bir gerekçeye dayanarak hukuka aykırı veri işleme yapılmasından; hatalı kurulumdan, amacı aşan kullanımdan, yanlış yapılandırmadan, yetersiz aydınlatmadan, saklama/erişim ihlalinden veya mevzuata aykırı satış ve uygulamadan münhasıran sorumludur. ZNA, TRASSIR markası ve ilgili ürün/yazılım sağlayıcıları, kendi kusur veya emredici hukuktan doğan sorumlulukları saklı kalmak kaydıyla, Bayi veya müşteri/son kullanıcının hukuka aykırı kullanımından kaynaklanan idari yaptırım, kamu zararı, ihaleden yasaklama, tazminat, ceza, talep, itibar kaybı veya masraftan sorumlu tutulamaz. Bayi; bu tür bir talep, inceleme, soruşturma veya ihtilafı en geç 24 saat içinde ZNA’ya yazılı bildirir; ZNA’nın makul talimatları doğrultusunda ilgili kullanımın durdurulması, teknik inceleme ve düzeltici işlemlerde iş birliği yapar; ZNA, TRASSIR markası ve ilgili sağlayıcıları her türlü talep, zarar, ceza ve makul vekalet/inceleme giderine karşı, kendi kusuru oranında, tazmin ve masun tutar.
8.10. Bildirim ve İş Birliği. Bayi, bu madde kapsamındaki bir olay veya makul risk şüphesini en geç 24 saat içinde ZNA’ya bildirir; ZNA’nın marka ve itibar koruma talimatlarına uygun davranır; gerekli bilgi ve belgeleri zamanında sunar.
8.11. Denetim. ZNA, makul bildirimle veya ağır risk halinde bildirimsiz olarak Bayi’nin ilgili kayıt, belge, sistem, personel ve alt yüklenici süreçlerini yalnızca sözleşme, marka ve itibar koruma yükümlülükleri bakımından denetleyebilir. İhlal tespit edilirse denetim ve düzeltme maliyetleri Bayi’ye aittir.
9. MARKA, FIKRI MÜLKIYET, LISANS VE TEKNIK HIZMETLER
9.1. Marka Kullanımı. Bayi, ZNA’ya ait logo, unvan, referans, ürün görseli, sertifika veya partnerlik ifadesini ancak ZNA’nın önceden yazılı onayıyla ve onaylı tasarımda kullanabilir. ZNA, onayı her zaman geri çekebilir.
9.2. Fikri Mülkiyet. Tüm marka, telif, tasarım, yazılım, kaynak kodu, teknik doküman, bilgi birikimi, teklif şablonu, konfigürasyon ve türev çalışma hakları ZNA’ya veya ilgili hak sahibine aittir. Bayi’ye mülkiyet devri olmaz.
9.3. Lisans. Yazılım/lisanslar yalnızca ilgili lisans koşulları, ZNA onayı ve tam ödeme sonrasında açılır veya devredilir. Bayi lisansı çoğaltamaz, tersine mühendislik yapamaz, kiralayamaz, alt lisans veremez veya yetkisiz kullanıcıya açamaz.
9.4. Destek Kapsamı. ZNA tarafından yazılı olarak kapsam altına alınmayan saha, kurulum, devreye alma, entegrasyon, eğitim, seyahat, konaklama, teknik keşif, PoC, acil müdahale ve 7/24 destek ücretlidir. Telefon ve çevrim içi destek, yazılı teklif/sipariş koşullarına tabidir.
9.5. Bayi Sorumluluğu. Bayi, müşteriye verdiği teknik ve ticari bilgilerin doğruluğundan; saha altyapısı, elektrik, ağ, depolama, üçüncü taraf uyumluluğu, güvenlik politikası ve yerinde iş sağlığı/güvenliği koşullarından sorumludur.
10. SORUMLULUK, TAZMINAT, SIGORTA VE MÜCBIR SEBEP
10.1. Sorumluluk Sınırı. ZNA; dolaylı zarar, kar kaybı, veri kaybı, itibar kaybı, iş kesintisi, fırsat kaybı, üçüncü kişi talebi veya beklenen tasarruf kaybından sorumlu değildir. ZNA’nın aynı siparişten doğabilecek toplam sorumluluğu, emredici hukuk kuralları saklı kalmak kaydıyla ilgili sipariş kapsamında ZNA’ya fiilen ödenen bedelle sınırlıdır.
10.2. Bayi Tazmini. Bayi; kendi yanlış beyanı, sözleşme ihlali, yetkisiz taahhüdü, ödeme temerrüdü, Deal Register ihlali, gizlilik/KVKK ihlali, etik ihlali, çalışanı veya alt yüklenicisi nedeniyle ZNA’nın uğrayacağı tüm zarar, ceza, talep, dava, avukatlık ve danışmanlık giderini ilk talepte karşılar. Bayi; özellikle biyometrik özellikli ürün ve çözümlerin hukuka aykırı veya amacı aşan kullanımı, mevzuata aykırı satış/kurulum/konfigürasyon, kamu ihalesi veya teknik şartnameye aykırı uygulama, aydınlatma veya açık rıza süreçlerinin hatalı yürütülmesi, saklama-erişim güvenliği eksikliği ve veri güvenliği ihlallerinden kaynaklanan tüm talep, idari yaptırım, kamu zararı, ihaleden yasaklama, tazminat ve masrafları da, ZNA’nın kendi kusuru veya emredici hukuktan doğan sorumluluğu saklı kalmak kaydıyla, derhal karşılayacak; ZNA, TRASSIR markası ve ilgili ürün/yazılım sağlayıcılarını bunlara karşı kendi kusuru oranında tazmin ve masun tutacaktır.
10.3. Sigorta. ZNA’nın talebi halinde Bayi; mesleki sorumluluk, ürün/saha sorumluluğu, işveren mali sorumluluk, siber risk veya proje riskine uygun sigortaları yaptırır ve poliçeleri ibraz eder.
10.4. Mücbir Sebep. Doğal afet, savaş, salgın, grev, siber saldırı, tedarik kesintisi, ithalat/ihracat kısıtı, resmi makam kararı, lojistik kesinti veya tarafın makul kontrolü dışındaki olaylar mücbir sebep sayılır. Mücbir sebep, ödeme yükümlülüğünü ortadan kaldırmaz; yalnızca doğrudan etkilediği ifayı makul süreyle erteler.
10.5. Zarar Azaltma. Taraflar, zarar doğurabilecek bir olayı fark ettiğinde etkisini azaltmak için makul önlem alır; Bayi, ZNA’nın yazılı talimatlarına uyar.
11. FESIH, ASKIYA ALMA VE FESIH SONRASI HÜKÜMLER
11.1. ZNA’nın Derhal Fesih Hakkı. ZNA; ödeme gecikmesi, teminat eksikliği, Deal Register baypası, gizlilik/KVKK ihlali, etik/uyum riski, rüşvet/yolsuzluk şüphesi, haksız rekabet, marka kötüye kullanımı, yanlış beyan, izinsiz devir, iflas/konkordato, müşteri verisinin yetkisiz kullanımı veya Bayi’nin itibar riski yaratması halinde bildirimle derhal fesih hakkına sahiptir.
11.2. Süreli Fesih. Taraflardan her biri, gerekçe göstermeksizin 30 gün önceden yazılı bildirimle sözleşmeyi feshedebilir. ZNA’nın feshi; Bayi’ye portföy, tazminat, komisyon, stok geri alımı veya gelecek kar kaybı hakkı vermez.
11.3. Fesih Sonrası. Fesih; Bayi’nin tüm borçlarını derhal muaccel kılar. Bayi, ZNA markası ve erişimlerini kullanmayı bırakır; gizli bilgi/verileri iade-imha eder; açık müşteri ve proje kayıtlarını ZNA’ya teslim eder; ZNA’nın talebiyle ödenmemiş ürünleri geri verir.
11.4. Devam Eden Hükümler. Gizlilik, KVKK, ödeme/tahsilat, fikri mülkiyet, tazmin, denetim, uyuşmazlık çözümü ve fesih sonrası yükümlülükler sözleşmenin sona ermesinden sonra da yürürlükte kalır.
12. İYI NIYET, İTIBAR, BILDIRIMLER VE SON HÜKÜMLER
12.1. İyi Niyet ve Profesyonel Davranış. Taraflar; şeffaflık, doğruluk, karşılıklı saygı, müşteri faydası, ticari nezaket, bilgi güvenliği ve sürdürülebilir iş birliği ilkelerine uyar. Bayi, ZNA veya iş ortakları hakkında doğrulanmamış, yanıltıcı, küçültücü veya itibarı zedeleyici açıklama yapmaz.
12.2. Müşteri İletişimi. Bayi, müşteri şikayeti, saha krizi, teslimat riski, teknik uygunsuzluk, tahsilat problemi, veri ihlali veya itibar riski doğurabilecek olayı gecikmeksizin ZNA’ya bildirir. ZNA’nın yazılı onayı olmadan kamu açıklaması yapmaz.
12.3. Devir ve Alt Yüklenici. Bayi, ZNA’nın önceden yazılı onayı olmadan sözleşmeyi, haklarını veya yükümlülüklerini devredemez; alt bayi/alt yüklenici kullanamaz. Onay verilmesi, Bayi’nin sorumluluğunu kaldırmaz.
12.4. Bildirimler. Tarafların imza bölümünde yer alan adresleri yasal bildirim adresidir. Değişiklik 3 iş günü içinde yazılı bildirilmezse eski adrese yapılan bildirim geçerlidir. KEP, noter, iadeli taahhütlü posta ve teyitli kurumsal e-posta yazılı bildirim sayılır.
12.5. Delil Sözleşmesi. Taraflar; ZNA’nın ticari defter, kayıt, ERP/CRM, Deal Register, e-posta, log, sunucu kaydı, kamera/erişim kaydı, teklif ve elektronik belgelerinin HMK kapsamında kesin delil niteliğinde olduğunu kabul eder.
12.6. Bölünebilirlik. Herhangi bir hükmün geçersizliği diğer hükümlerin geçerliliğini etkilemez. Geçersiz hüküm, ekonomik amaca en yakın geçerli hükümle yorumlanır.
12.7. Uygulanacak Hukuk ve Yetki. İşbu sözleşmeye Türk hukuku uygulanır. Uyuşmazlıklarda İstanbul Anadolu Mahkemeleri ve İcra Daireleri yetkilidir. Dava şartı arabuluculuk hükümleri saklıdır.
12.8. Yürürlük. İşbu sözleşme 12 ana bölüm, 79 madde ve imza sayfasından oluşur; Taraflarca okunarak serbest iradeyle imzalandığı tarihte yürürlüğe girer.

13. TARAF BİLGİLERİ VE İMZALAR
Taraflar, aşağıdaki bilgilerin doğru olduğunu, değişiklikleri en geç 3 iş günü içinde yazılı olarak bildireceğini ve bu sözleşmenin tüm hükümlerini okuyarak kabul ettiğini beyan eder.

ZNA
  Ticari Unvan : ZNA Teknoloji Bilişim Hizmetleri Sanayi ve Ticaret Ltd. Şti.
  Adres        : Başakşehir / İstanbul
  Yetkili Kişi : {{imza_yetkilisi}}

BAYİ
  Ticari Unvan     : {{bayi_unvani}}
  Vergi Dairesi/No : {{bayi_vergi_dairesi}} / {{bayi_vergi_no}}
  MERSİS No        : {{bayi_mersis_no}}
  Ticaret Sicil No : {{bayi_ticaret_sicil_no}}
  Adres            : {{bayi_adresi}}
  KEP / E-posta    : {{bayi_kep_adresi}} / {{bayi_eposta}}
  Yetkili Kişi     : {{bayi_yetkili_adi}} — {{bayi_yetkili_unvani}}
  Telefon          : {{bayi_telefon}}

ZNA TEKNOLOJİ                                     BAYİ: {{bayi_unvani}}
Yetkili: {{imza_yetkilisi}}                       Yetkili: {{bayi_yetkili_adi}}
Tarih: {{sozlesme_tarihi}}                        Tarih: {{sozlesme_tarihi}}
Kaşe / İmza:                                      Kaşe / İmza:$SABLON$,
    versiyon = versiyon + 1,
    guncelleme_tarih = now()
where ad = 'Yetkili Dış Bayilik ve Deal Register Sözleşmesi';
