-- 204: İK modülü — bordrolar + izin talepleri (Abdullah İğde için yönetim, herkes için kişisel)
-- GİZLİLİK: bordro satır + dosya erişimi DB seviyesinde "kendi kaydı VEYA İK yetkisi".
-- İK yetkisi = rol admin VEYA moduller içinde 'ik_yonetim' (Abdullah id 44'e burada verilir).

-- ── Yetki yardımcısı ────────────────────────────────────────────────────────
create or replace function public.ik_yetkili()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from kullanicilar
    where auth_id = auth.uid()
      and (rol = 'admin' or 'ik_yonetim' = any(coalesce(moduller, '{}')))
  );
$$;
revoke execute on function public.ik_yetkili() from anon;

-- Kendi kullanıcı id'si (bigint) — satır sahipliği kontrolü için
create or replace function public.ik_kendi_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from kullanicilar where auth_id = auth.uid() limit 1;
$$;
revoke execute on function public.ik_kendi_id() from anon;

-- ── Bordrolar ───────────────────────────────────────────────────────────────
create table if not exists public.bordrolar (
  id bigint generated by default as identity primary key,
  kullanici_id bigint not null references public.kullanicilar(id) on delete cascade,
  donem_yil int not null check (donem_yil between 2020 and 2100),
  donem_ay int not null check (donem_ay between 1 and 12),
  dosya_yol text not null,
  dosya_ad text,
  aciklama text,
  yukleyen_id bigint references public.kullanicilar(id),
  olusturma_tarih timestamptz not null default now(),
  unique (kullanici_id, donem_yil, donem_ay)
);
alter table public.bordrolar enable row level security;

drop policy if exists bordro_sel on public.bordrolar;
create policy bordro_sel on public.bordrolar for select
  using (kullanici_id = public.ik_kendi_id() or public.ik_yetkili());

drop policy if exists bordro_ins on public.bordrolar;
create policy bordro_ins on public.bordrolar for insert
  with check (public.ik_yetkili());

drop policy if exists bordro_upd on public.bordrolar;
create policy bordro_upd on public.bordrolar for update
  using (public.ik_yetkili());

drop policy if exists bordro_del on public.bordrolar;
create policy bordro_del on public.bordrolar for delete
  using (public.ik_yetkili());

-- ── İzin talepleri ──────────────────────────────────────────────────────────
create table if not exists public.izin_talepleri (
  id bigint generated by default as identity primary key,
  kullanici_id bigint not null references public.kullanicilar(id) on delete cascade,
  tur text not null default 'yillik'
    check (tur in ('yillik', 'mazeret', 'rapor', 'ucretsiz', 'diger')),
  baslangic date not null,
  bitis date not null,
  gun_sayisi numeric(5,1) not null check (gun_sayisi > 0),
  aciklama text,
  durum text not null default 'bekliyor'
    check (durum in ('bekliyor', 'onaylandi', 'reddedildi', 'iptal')),
  onaylayan_id bigint references public.kullanicilar(id),
  onay_tarihi timestamptz,
  karar_notu text,
  olusturma_tarih timestamptz not null default now(),
  check (bitis >= baslangic)
);
alter table public.izin_talepleri enable row level security;
create index if not exists izin_talepleri_kullanici_ix on public.izin_talepleri (kullanici_id, durum);

drop policy if exists izin_sel on public.izin_talepleri;
create policy izin_sel on public.izin_talepleri for select
  using (kullanici_id = public.ik_kendi_id() or public.ik_yetkili());

-- Personel yalnız KENDİ adına talep açar; İK herkese açabilir
drop policy if exists izin_ins on public.izin_talepleri;
create policy izin_ins on public.izin_talepleri for insert
  with check (kullanici_id = public.ik_kendi_id() or public.ik_yetkili());

-- İK karar verir; personel yalnız BEKLEYEN talebini güncelleyebilir (iptal için)
drop policy if exists izin_upd on public.izin_talepleri;
create policy izin_upd on public.izin_talepleri for update
  using (public.ik_yetkili() or (kullanici_id = public.ik_kendi_id() and durum = 'bekliyor'));

drop policy if exists izin_del on public.izin_talepleri;
create policy izin_del on public.izin_talepleri for delete
  using (public.ik_yetkili());

-- ── Bordro dosya deposu (private bucket) ────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('bordrolar', 'bordrolar', false)
on conflict (id) do nothing;

-- Dosya yolu sözleşmesi: {kullanici_id}/{yil}-{ay}-{rastgele}.pdf
-- Okuma: yol kendi kullanıcı id klasörüyse VEYA İK yetkilisi
drop policy if exists bordro_dosya_sel on storage.objects;
create policy bordro_dosya_sel on storage.objects for select
  using (
    bucket_id = 'bordrolar'
    and ((storage.foldername(name))[1] = public.ik_kendi_id()::text or public.ik_yetkili())
  );

drop policy if exists bordro_dosya_ins on storage.objects;
create policy bordro_dosya_ins on storage.objects for insert
  with check (bucket_id = 'bordrolar' and public.ik_yetkili());

drop policy if exists bordro_dosya_del on storage.objects;
create policy bordro_dosya_del on storage.objects for delete
  using (bucket_id = 'bordrolar' and public.ik_yetkili());

-- ── Abdullah İğde'ye (id 44) İK modülü ──────────────────────────────────────
update public.kullanicilar
   set moduller = array_append(coalesce(moduller, '{}'), 'ik_yonetim')
 where id = 44
   and not ('ik_yonetim' = any(coalesce(moduller, '{}')));

notify pgrst, 'reload schema';

select 'mig 204 tamam' as durum,
  (select count(*) from kullanicilar where 'ik_yonetim' = any(coalesce(moduller,'{}'))) as ik_yetkili_sayisi;
