-- 308: Teklif taslagi localStorage -> DB (18.08.2026)
-- Ahmet/Turkuaz vakasi: yeni teklif kaydedilmeden kayboldu, yerel taslak
-- cihaza ozeldi ve bulunamadi. Taslak artik sunucuda: kullanici basina TEK
-- yeni-teklif taslagi, her cihazdan erisilir, Teklifler listesinde serit olur.

create table if not exists public.teklif_taslaklari (
  id bigint generated by default as identity primary key,
  kullanici_id bigint not null unique references public.kullanicilar(id) on delete cascade,
  form jsonb not null,
  guncelleme_tarih timestamptz not null default now()
);

alter table public.teklif_taslaklari enable row level security;

-- Herkes YALNIZ kendi taslagini gorur/yazar/siler (kisiye ozel; is_staff degil).
-- (select ...) sarmali: RLS initplan performans kurali.
drop policy if exists teklif_taslak_sahibi on public.teklif_taslaklari;
create policy teklif_taslak_sahibi on public.teklif_taslaklari
  for all
  using (kullanici_id = (select k.id from public.kullanicilar k where k.auth_id = (select auth.uid())))
  with check (kullanici_id = (select k.id from public.kullanicilar k where k.auth_id = (select auth.uid())));

grant select, insert, update, delete on public.teklif_taslaklari to authenticated;

notify pgrst, 'reload schema';
